# numpy tutorial

In [1]:
import numpy as np

In [4]:
print("hello riya")

hello riya


In [15]:
arr=np.array([3,6,99999999,10],np.int64)

In [14]:
arr

array([ 3,  6, -1, 10], dtype=int8)

In [16]:
arr[0]

3

In [17]:
arr.shape

(4,)

In [18]:
arr.dtype

dtype('int64')

In [21]:
arr[3]=99

In [22]:
arr

array([       3,        6, 99999999,       99], dtype=int64)

** Array creation meth 1 : conversion from other python strucures

In [25]:
listArr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [26]:
listArr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
listArr.dtype

dtype('int32')

In [28]:
listArr.shape

(3, 3)

In [29]:
listArr.size

9

In [31]:
np.array({34,35,36})

array({34, 35, 36}, dtype=object)

** Array creation meth 2 : intrinsic numpy array creation objects

In [32]:
zeros=np.zeros((2,5))

In [33]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
zeros.shape

(2, 5)

In [35]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
rng=np.arange(10)

In [37]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
lsp=np.linspace(1,5,5)

In [41]:
lsp

array([1., 2., 3., 4., 5.])

In [43]:
emp=np.empty((4,4))

In [44]:
emp

array([[4.67296746e-307, 1.69121096e-306, 1.86921279e-306,
        8.34441742e-308],
       [1.78022342e-306, 6.23058028e-307, 9.79107872e-307,
        6.89807188e-307],
       [7.56594375e-307, 6.23060065e-307, 1.78021527e-306,
        8.34454050e-308],
       [1.11261027e-306, 1.15706896e-306, 1.33512173e-306,
        1.33504432e-306]])

In [45]:
id=np.identity(9)

In [46]:
id

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [47]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
ar=np.arange(99)

In [49]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [50]:
ar.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [51]:
ar.reshape(33,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89],
       [90, 91, 92],
       [93, 94, 95],
       [96, 97, 98]])

In [52]:
ar.shape

(99,)

In [53]:
id.ravel()

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [55]:
ara=np.array([[1,2,3],[4,5,6],[7,1,0]])

In [56]:
ara

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [57]:
ara.sum(axis=0)

array([12,  8,  9])

In [58]:
ara.sum(axis=1)

array([ 6, 15,  8])

In [59]:
ara.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [60]:
ara.flat

In [62]:
for i in ara.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [63]:
ara.ndim

2

In [64]:
ara.size

9

In [65]:
ara.shape

(3, 3)

In [66]:
ara.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [67]:
ar.nbytes

396

In [68]:
ara.argmax()

6

In [69]:
ara.argmin()

8

In [70]:
ara.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)